telegram:
  use_html: true

territories:
  moscow:
    name: "Москва"
    thread_id: 3
    search_radius_km: 50
    cities: ["москва"]
    keywords:
      vk: "событие москва"
      google: "события в москве"
    metro_available: true
  
  yaroslavl:
    name: "Ярославль"
    thread_id: 4
    search_radius_km: 50
    cities: ["ярославль"]
    keywords:
      vk: "событие ярославль"
      google: "события ярославль"
    metro_available: false

  tver:
    name: "Тверь"
    thread_id: 7
    search_radius_km: 50
    cities: ["Тверь"]
    keywords:
      vk: "события тверь"
      google: "события в твери"
    metro_available: false 

  EKB:
    name: "Екатеринбург"
    thread_id: 9
    search_radius_km: 500
    cities: ["Екатеринбург]
    keywords:
      vk: "события Екатеринбурге"
      google: "события в Екатеринбурге"
    metro_available: true

  SPB:
    name: "Санкт-Петербург"
    thread_id: 10
    search_radius_km: 50
    cities: ["Санкт-Петербург"]
    keywords:
      vk: "события Санкт-Петербурге"
      google: "события в Санкт-Петербурге"
    metro_available: true

  DV:
    name: "Дальний восток"
    thread_id: 6
    search_radius_km: 700
    cities: ["Петропавловск-Камчатский", "Владивосток"]
    keywords:
      vk: "события Владивостоа, события в Петропавловске-Камчатском"
      google: "события Владивостоа, события в Петропавловске-Камчатском"
    metro_available: false

  KK:
    name: "Краснодарский край"
    thread_id: 8
    search_radius_km: 700
    cities: ["Сочи", "Краснодар"]
    keywords:
      vk: "события Сочи, события в Краснодаре, события в Геленджике, события в Анапе"
      google: "события Сочи, события в Геленджик, события Анапа"
    metro_available: false

collections:
  free_today:
    name: "🆓 Бесплатные события на сегодня"
    description: "Бесплатные события где люди могут общаться"
    is_free: true
    max_count: 50
  
  paid_today:
    name: "💳 События до 1000₽ на сегодня"
    description: "Платные события до 1000 рублей"
    is_free: false
    max_price: 1000
    max_count: 30
